### ISSUE TITLE
Problem with your save editor of Zelda Triforce Heroes

### ISSUE THREAD

**Issue by GeetaArmstrong** [kwsch/ZTFH_SE#1]
Hello! Today I've downloaded your save editor and everything seems fine until I've go to play online and I've see my name says "Link " (with the empty spaces) Dunno why. When I try to edit it on the save editor it stills says the same. I hope you can fix this and thank you for reading this.

**Comment by kwsch** [comment]
Should be fixed in the latest commit https://github.com/kwsch/ZTFH_SE/commit/ad0f6d36a2a6907f948464e1b60d3bac7e285978 / release https://github.com/kwsch/ZTFH_SE/releases/tag/0.6.
